library(rmarkdown)
render("tf2cmbr_wtcmbr/tf2cmbr_wtcmbr.Rmd", "pdf_document")
render("tf2ambr_wtaother/wtambr_wtaother.Rmd", "pdf_document")
render("wtambr_wtbmbr/wtambr_wtbmbr.Rmd", "pdf_document")
render("wtambr_wtcmbr/wtambr_wtcmbr.Rmd", "pdf_document")
render("wtbmbr_wtbother.attempt2/wtbmbr_wtbother.attempt2.Rmd", "pdf_document")
render("wtbmbr_wtcmbr/wtbmbr_wtcmbr.Rmd", "pdf_document")
render("wtcmbr_wtcother/wtcmbr_wtcother.Rmd", "pdf_document")
